$script_mysql = <<-SCRIPT
    apt-get update && \
    apt-get install -y mysql-server-5.7 && \
    mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest:80, host:8080
    #config.vm.network "private_network", type: "dhcp"
    #config.vm.network "private_network", ip: "192.168.56.4"
    #config.vm.network "public_network" # esta opção pega o dchp da rede do host
    config.vm.network "public_network", ip: "192.168.1.60" # cuidado ao escolher o ip para não dar conflito
    
    #config.vm.provision "shell", inline: "echo Hello, Word"
    #config.vm.provision "shell", inline: "echo Hello, Word >> hello.txt"
    
    #config.vm.provision "shell",
        #inline: "cat /diretorio/chave_pub >> .ssh/authorized_keys" #automatizando a copia da chave pública

    config.vm.provision "shell", inline: $script_mysql
    config.vm.provision "shell",
        inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf" # comando para substituir um arquivo usando o shell
    config.vm.provision "shell",
        inline: "service mysql restart"

    #config.vm.synced_folder "./configs", "/configs" # novo compartilhamento: "diretório_local", "diretório_VM"
    #config.vm.synced_folder ".", "/vagrant", disabled: true # desativando compartilhamento anterior
end