$script_mysql = <<-SCRIPT
    apt-get update && \
    apt-get install -y mysql-server-5.7 && \
    mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.define "mysql" do |mysql| # cada "define" é uma máquina nova
        mysql.vm.network "public_network", ip: "192.168.1.60" # cuidado ao escolher o ip para não dar conflito
       
        #mysql.vm.provision "shell",
            #inline: "cat /configs/id_bionic.pub >> .ssh/authorized_keys" #automatizando a copia da chave pública

        mysql.vm.provision "shell", inline: $script_mysql
        mysql.vm.provision "shell",
            inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf" # comando para substituir um arquivo usando o shell
        mysql.vm.provision "shell",
            inline: "service mysql restart"

        mysql.vm.synced_folder "./configs", "/configs"    
        mysql.vm.synced_folder ".", "/vagrant", disabled: true
    end

    config.vm.define "phpweb" do |phpweb|
        phpweb.vm.network "forwarded_port", guest:8888, host:8888
        phpweb.vm.network "public_network", ip: "192.168.1.61"

        phpweb.vm.provision "shell",
            inline: "apt-get update && apt-get install -y puppet"
        
        #vamos criar um provision para integrar o vagrant com o puppet e já passar
        #o caminho de configuração
        phpweb.vm.provision "puppet" do |puppet|
            puppet.manifests_path = "./configs/manifests_puppet"
            puppet.manifest_file = "phpweb.pp"
        end

    end
end