Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest:80, host:8080
    #config.vm.network "private_network", type: "dhcp"
    #config.vm.network "private_network", ip: "192.168.56.4"
    config.vm.network "public_network" # esta opção pega o dchp da rede do host
    #config.vm.network "public_network", ip: "192.168.1.60" # cuidado ao escolher o ip para não dar conflito
end